kind: SwitchConfig
version: v1alpha1
kubeconfigName: "*.myconfig"
kubeconfigStores:

- kind: azure
  config:
    subscriptionID: xxxx
  cache:
    kind: filesystem
    config:
      path: ~/.kube/cache


- kind: rancher
  id: my-rancher-id
  config:
    rancherAPIAddress: https://my-rancher.com
    rancherToken: token-4mdw5:my-token
  cache:
    kind: filesystem
    config:
      path: ~/.kube/cache

- kind: eks
  config:
    profile: default
    region: us-east-1
  cache:
    kind: filesystem
    config:
      path: ~/.kube/cache

- kind: gke
  config:
    authentication:
      authenticationType: gcloud
  cache:
    kind: filesystem
    config:
      path: ~/.kube/cache
